name: Documentation

on:
  pull_request:
  push:
    branches: main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    # Force to use color
    FORCE_COLOR: true
    BROWSER: /usr/bin/firefox
    DISPLAY: :99.0
    
permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install .[doc,plotting]
      - name: Sphinx build
        id: build-docs
        run: |
          cd doc_conf & make html 
      - name: Upload documentation
        if: steps.build-docs.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: DocHTML
          path: doc/_build/html

  deploy_on_main:
    runs-on: ubuntu-latest
    needs: [build_docs]
    if: ${{ contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)}}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: DocHTML
          path: doc/_build/html
      - name: Commit to main
        run: |
          git clone --depth 1 https://github.com/${{ github.repository_owner }}/hidimstat.git
          rm -Rf hidimstat/docs
          mkdir hidimstat/docs
          cp -r doc/_build/html/* hidimstat/docs
          cd hidimstat
          touch docs/.nojekyll
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: hidimstat
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
