# For more information see: https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Lint

on:
  # Allows you to run this workflow from another workflow
  workflow_call

# disable all the permission for the workflow
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      # Codespell check
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Run codespell with pyproject.toml config
        run: |
          pip install .[style]
          codespell --toml pyproject.toml

      # Ruff check
      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"

      - run: ruff check --fix
      - run: ruff format
